# Generated by Django 5.0.1 on 2024-03-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
