# Generated by Django 4.2.5 on 2024-03-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0002_auction_spice_bid_auction_spice_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_proof',
            field=models.FileField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
