# Generated by Django 4.2.4 on 2024-03-21 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapi', '0003_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='spice',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
